title: Adeline Southard
#logo: /assets/img/me_img.png
#description: text below image
show_downloads: false
theme: jekyll-theme-minimal
sidebar:
  - title: "Title"
    image: "/assets/images/your-image.jpg"
    image_alt: "image"
    text: "Some text here."
  - title: "Another Title"
    text: "More text here."
    nav: sidebar-sample
